# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 06:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_prisoner', '0002_player_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='partner_id',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
