# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 09:40
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_prisoner', '0004_player_partner_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_payoff',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
