# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-11 09:42
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_prisoner', '0005_player_total_payoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='total_payoff',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
