# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 06:55
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0002_player_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
