# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0003_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
