# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 08:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0004_remove_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choice_01',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
    ]
