# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 09:22
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0005_player_choice_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='label',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
