# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 09:58
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0006_player_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='testNumber',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
