# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 10:01
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0007_player_testnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='testNumber',
        ),
        migrations.AddField(
            model_name='player',
            name='aaa',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
