# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 11:32
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0009_remove_player_aaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choice_02',
            field=otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y')], max_length=10000, null=True),
        ),
    ]
