# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-08 12:06
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0011_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='count',
        ),
        migrations.AddField(
            model_name='player',
            name='correct',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
