# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 09:06
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0012_auto_20180408_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='choice_01',
        ),
        migrations.AddField(
            model_name='player',
            name='id_choice_01',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
    ]
