# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 01:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0013_auto_20180514_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_choice_01',
        ),
        migrations.AddField(
            model_name='player',
            name='choice_01',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='label_partner',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
