# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 01:47
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0014_auto_20180516_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='choice_01',
        ),
        migrations.RemoveField(
            model_name='player',
            name='choice_02',
        ),
        migrations.AddField(
            model_name='player',
            name='co_choice_01',
            field=otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='id_choice_01',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
    ]
