# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 01:56
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0015_auto_20180516_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='co_choice_01',
            field=otree.db.models.StringField(choices=[('"主"角色', '"主"角色'), ('"从"角色', '"从"角色')], max_length=10000, null=True),
        ),
    ]
