# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 02:07
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0016_auto_20180516_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='co_choice_02',
            field=otree.db.models.StringField(choices=[('"主"角色', '"主"角色'), ('"从"角色', '"从"角色')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='co_choice_03',
            field=otree.db.models.StringField(choices=[('"主"角色', '"主"角色'), ('"从"角色', '"从"角色')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='co_choice_04',
            field=otree.db.models.StringField(choices=[('"主"角色', '"主"角色'), ('"从"角色', '"从"角色')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='co_choice_05',
            field=otree.db.models.StringField(choices=[('"主"角色', '"主"角色'), ('"从"角色', '"从"角色')], max_length=10000, null=True),
        ),
    ]
