# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 02:20
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0017_auto_20180516_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pay_round',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
