# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 02:50
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0018_player_pay_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='co_payoff_points',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
