# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 03:00
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0019_player_co_payoff_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your gender?'),
        ),
    ]
