# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 03:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0020_player_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q01',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（1） 50%的可能性，你将损失50实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q02',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（2） 50%的可能性，你将损失75实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q03',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（3） 50%的可能性，你将损失100实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q04',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（4） 50%的可能性，你将损失125实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q05',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（5） 50%的可能性，你将损失150实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q06',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（6） 50%的可能性，你将损失170实验币；50%可能，你将得到150实验币'),
        ),
    ]
