# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 03:26
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0026_auto_20180527_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sur_gender',
            field=otree.db.models.StringField(choices=[('男', '男'), ('女', '女')], max_length=10000, null=True),
        ),
    ]
