# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 03:29
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0031_auto_20180527_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sur_grade',
            field=otree.db.models.StringField(choices=[('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四'), ('研一', '研一'), ('研二', '研二')], max_length=10000, null=True, verbose_name='你就读的年级为'),
        ),
    ]
