# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 03:31
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0034_player_sur_party_menber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sur_party_menber',
            field=otree.db.models.StringField(choices=[('是', '是'), ('否', '否')], max_length=10000, null=True, verbose_name='你是否为党员'),
        ),
    ]
