# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 05:24
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0039_player_sur_project_01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sur_project_01',
            field=otree.db.models.StringField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
