# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 05:24
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0041_auto_20180527_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sur_project_02',
            field=otree.db.models.StringField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3')], max_length=10000, null=True, verbose_name='你会选择'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_project_03',
            field=otree.db.models.StringField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3')], max_length=10000, null=True, verbose_name='你会选择'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_project_04',
            field=otree.db.models.StringField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3')], max_length=10000, null=True, verbose_name='你会选择'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_project_05',
            field=otree.db.models.StringField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3')], max_length=10000, null=True, verbose_name='你会选择'),
        ),
    ]
