# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 08:52
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0043_auto_20180527_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sur_q07',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（6） 50%的可能性，你将损失170实验币；50%可能，你将得到150实验币'),
        ),
        migrations.AddField(
            model_name='player',
            name='sur_q08',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（6） 50%的可能性，你将损失170实验币；50%可能，你将得到150实验币'),
        ),
    ]
