# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 07:10
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0048_auto_20180527_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sur_q07',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（7） 50%的可能，你将损失60实验币；50%可能，你将得到50实验币'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sur_q08',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（8） 50%的可能，你将损失70实验币；50%可能，你将得到50实验币'),
        ),
    ]
