# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 08:10
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0054_auto_20180601_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sur_q03',
            field=otree.db.models.StringField(choices=[('接受', '接受'), ('拒绝', '拒绝')], max_length=10000, null=True, verbose_name='（3） 50%的可能，你将得到0个实验币；50%可能，你将得到130实验币'),
        ),
    ]
