# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-14 05:58
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('informal_authority', '0056_auto_20180601_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='treatment',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
