# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_separation_group', to='otree.Session')),
            ],
            options={
                'db_table': 'preference_separation_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('will_compete_01', otree.db.models.BooleanField(choices=[[True, '比赛'], [False, '不比赛']])),
                ('total_01', otree.db.models.PositiveIntegerField(null=True)),
                ('correct_01', otree.db.models.PositiveIntegerField(null=True)),
                ('result_01', otree.db.models.StringField(choices=[('赢了', '赢了'), ('一样多', '一样多'), ('输了', '输了')], max_length=10000, null=True)),
                ('profit_01', otree.db.models.CurrencyField(null=True)),
                ('partner_01', otree.db.models.StringField(max_length=10000, null=True)),
                ('intro_q1', otree.db.models.IntegerField(choices=[[1, '10对全部支付'], [2, '随机选择其中一对支付']], null=True)),
                ('intro_q2', otree.db.models.IntegerField(choices=[[1, '确定m元'], [2, '确定n元'], [3, 'm元或n元，由计算机根据它们的概率随机决定']], null=True)),
                ('g2_q1', otree.db.models.StringField(choices=[['A', '1/10的概率获得20元， 9/10的概率获得16元；'], ['B', '1/10的概率获得38.5元， 9/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q2', otree.db.models.StringField(choices=[['A', '2/10的概率获得20元， 8/10的概率获得16元；'], ['B', '2/10的概率获得38.5元， 8/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q3', otree.db.models.StringField(choices=[['A', '3/10的概率获得20元， 7/10的概率获得16元；'], ['B', '3/10的概率获得38.5元， 7/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q4', otree.db.models.StringField(choices=[['A', '4/10的概率获得20元， 6/10的概率获得16元；'], ['B', '4/10的概率获得38.5元， 6/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q5', otree.db.models.StringField(choices=[['A', '5/10的概率获得20元， 5/10的概率获得16元；'], ['B', '5/10的概率获得38.5元， 5/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q6', otree.db.models.StringField(choices=[['A', '6/10的概率获得20元， 4/10的概率获得16元；'], ['B', '6/10的概率获得38.5元， 4/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q7', otree.db.models.StringField(choices=[['A', '7/10的概率获得20元， 3/10的概率获得16元；'], ['B', '7/10的概率获得38.5元， 3/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q8', otree.db.models.StringField(choices=[['A', '8/10的概率获得20元， 2/10的概率获得16元；'], ['B', '8/10的概率获得38.5元， 2/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q9', otree.db.models.StringField(choices=[['A', '9/10的概率获得20元， 1/10的概率获得16元；'], ['B', '9/10的概率获得38.5元， 1/10的概率获得1元；']], max_length=10000, null=True)),
                ('g2_q10', otree.db.models.StringField(choices=[['A', '10/10的概率获得20元， 0/10的概率获得16元；'], ['B', '10/10的概率获得38.5元， 0/10的概率获得1元；']], max_length=10000, null=True)),
                ('payoff_02_num', otree.db.models.PositiveIntegerField(null=True)),
                ('profit_02', otree.db.models.CurrencyField(null=True)),
                ('ans_02', otree.db.models.StringField(max_length=10000, null=True)),
                ('will_compete_03', otree.db.models.BooleanField(choices=[[True, '比赛'], [False, '不比赛']])),
                ('partner_03', otree.db.models.StringField(max_length=10000, null=True)),
                ('total_03', otree.db.models.PositiveIntegerField(null=True)),
                ('correct_03', otree.db.models.PositiveIntegerField(null=True)),
                ('result_03', otree.db.models.StringField(choices=[('赢了', '赢了'), ('一样多', '一样多'), ('输了', '输了')], max_length=10000, null=True)),
                ('profit_03', otree.db.models.CurrencyField(null=True)),
                ('g4_q1', otree.db.models.StringField(choices=[['A', '1/10的概率获得20元， 9/10的概率获得16元；'], ['B', '1/10的概率获得38.5元， 9/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q2', otree.db.models.StringField(choices=[['A', '2/10的概率获得20元， 8/10的概率获得16元；'], ['B', '2/10的概率获得38.5元， 8/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q3', otree.db.models.StringField(choices=[['A', '3/10的概率获得20元， 7/10的概率获得16元；'], ['B', '3/10的概率获得38.5元， 7/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q4', otree.db.models.StringField(choices=[['A', '4/10的概率获得20元， 6/10的概率获得16元；'], ['B', '4/10的概率获得38.5元， 6/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q5', otree.db.models.StringField(choices=[['A', '5/10的概率获得20元， 5/10的概率获得16元；'], ['B', '5/10的概率获得38.5元， 5/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q6', otree.db.models.StringField(choices=[['A', '6/10的概率获得20元， 4/10的概率获得16元；'], ['B', '6/10的概率获得38.5元， 4/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q7', otree.db.models.StringField(choices=[['A', '7/10的概率获得20元， 3/10的概率获得16元；'], ['B', '7/10的概率获得38.5元， 3/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q8', otree.db.models.StringField(choices=[['A', '8/10的概率获得20元， 2/10的概率获得16元；'], ['B', '8/10的概率获得38.5元， 2/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q9', otree.db.models.StringField(choices=[['A', '9/10的概率获得20元， 1/10的概率获得16元；'], ['B', '9/10的概率获得38.5元， 1/10的概率获得1元；']], max_length=10000, null=True)),
                ('g4_q10', otree.db.models.StringField(choices=[['A', '10/10的概率获得20元， 0/10的概率获得16元；'], ['B', '10/10的概率获得38.5元， 0/10的概率获得1元；']], max_length=10000, null=True)),
                ('payoff_04_num', otree.db.models.PositiveIntegerField(null=True)),
                ('profit_04', otree.db.models.CurrencyField(null=True)),
                ('ans_04', otree.db.models.StringField(max_length=10000, null=True)),
                ('pay_round_01', otree.db.models.PositiveIntegerField(null=True)),
                ('pay_round_02', otree.db.models.PositiveIntegerField(null=True)),
                ('payoff_plus_fee', otree.db.models.CurrencyField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preference_separation.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_separation_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_separation_player', to='otree.Session')),
            ],
            options={
                'db_table': 'preference_separation_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_separation_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'preference_separation_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference_separation.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference_separation.Subsession'),
        ),
    ]
